import { TOKEN_CONTRACT } from '../tokens/contract';
const appearanceVariables = new Set<string>([
  ...Object.values(TOKEN_CONTRACT),
  '--zy-control-icon-size',
]);

/** Stable component hooks. Theme packages cannot supply selectors or behavior. */
export const COMPONENT_SELECTORS = {
  button: '.theme-button',
  'button-default': '.theme-button-default',
  'button-outline': '.theme-button-outline',
  'button-secondary': '.theme-button-secondary',
  'button-ghost': '.theme-button-ghost',
  'button-prompt-selector': '.theme-button-prompt-selector',
  'button-navigation': '.theme-button-navigation',
  'button-toolbar': '.theme-button-toolbar',
  'button-destructive': '.theme-button-destructive',
  'button-link': '.theme-button-link',
  'button-appearance': '.theme-button-appearance',
  'button-size-default': '.theme-button-size-default',
  'button-size-xs': '.theme-button-size-xs',
  'button-size-sm': '.theme-button-size-sm',
  'button-size-lg': '.theme-button-size-lg',
  'button-size-appearance': '.theme-button-size-appearance',
  'button-size-navigation': '.theme-button-size-navigation',
  'button-size-icon': '.theme-button-size-icon',
  'button-size-icon-xs': '.theme-button-size-icon-xs',
  'button-size-icon-sm': '.theme-button-size-icon-sm',
  'button-size-icon-lg': '.theme-button-size-icon-lg',
  'select-trigger': '.theme-select-trigger',
  'select-trigger-small': '.theme-select-trigger[data-size="sm"]',
  'select-item': '.theme-select-item',
  'select-label': '.theme-select-label',
  'select-separator': '.theme-select-separator',
  'select-scroll': '.theme-select-scroll',
  'select-icon': '.theme-select-icon',
  'select-content': '.theme-select-content',
  badge: '.theme-badge',
  'badge-default': '.theme-badge-default',
  'badge-secondary': '.theme-badge-secondary',
  'badge-destructive': '.theme-badge-destructive',
  'badge-outline': '.theme-badge-outline',
  'badge-ghost': '.theme-badge-ghost',
  'badge-link': '.theme-badge-link',
  'badge-default-link': '.theme-badge-default:any-link',
  'badge-secondary-link': '.theme-badge-secondary:any-link',
  'badge-destructive-link': '.theme-badge-destructive:any-link',
  'badge-outline-link': '.theme-badge-outline:any-link',
  card: '.theme-card',
  'card-header': '.theme-card-header',
  'card-title': '.theme-card-title',
  'card-description': '.theme-card-description',
  'card-content': '.theme-card-content',
  'card-footer': '.theme-card-footer',
  'dialog-content': '.theme-dialog-content',
  'dialog-overlay': '.theme-dialog-overlay',
  'dialog-title': '.theme-dialog-title',
  'dialog-description': '.theme-dialog-description',
  'dialog-footer': '.theme-dialog-footer',
  'popover-content': '.theme-popover-content',
  'popover-title': '.theme-popover-title',
  'popover-description': '.theme-popover-description',
  'popover-header': '.theme-popover-header',
  'card-small': '.theme-card[data-size="sm"]',
  'card-interactive': '.theme-card:is([role="button"], a[href], button)',
  'card-title-small': '.theme-card[data-size="sm"] .theme-card-title',
  'dialog-immediate': '.theme-dialog-immediate',
  'input-group': '.theme-input-group',
  'input-group-addon': '.theme-input-group-addon',
  'input-group-text': '.theme-input-group-text',
  command: '.theme-command',
  'command-input': '.theme-command-input',
  'command-palette-input': '.theme-command-palette-input',
  'command-input-group': '.theme-command-input-group',
  'command-item': '.theme-command-item',
  'command-item-selector': '.theme-command-item-selector',
  'command-item-palette': '.theme-command-item-palette',
  'command-empty': '.theme-command-empty',
  'command-group': '.theme-command-group',
  'command-separator': '.theme-command-separator',
  'command-shortcut': '.theme-command-shortcut',
  'task-search-dialog': '.theme-task-search-dialog',
  'command-heading': '.theme-command-group [cmdk-group-heading]',
  'menu-content': '.theme-menu-content',
  'menu-motion': '.theme-menu-motion',
  'menu-item': '.theme-menu-item',
  'menu-sub-trigger': '.theme-menu-sub-trigger',
  'menu-sub-content': '.theme-menu-sub-content',
  'menu-check-item': '.theme-menu-check-item',
  'menu-label': '.theme-menu-label',
  'menu-separator': '.theme-menu-separator',
  'menu-shortcut': '.theme-menu-shortcut',
  'menu-destructive': '.theme-menu-item[data-variant="destructive"]',
  'menu-inset': ':is(.theme-menu-item,.theme-menu-label)[data-inset="true"]',
  'sheet-content': '.theme-sheet-content',
  'sheet-overlay': '.theme-sheet-overlay',
  'sheet-title': '.theme-sheet-title',
  'sheet-description': '.theme-sheet-description',
  'sheet-header': '.theme-sheet-header',
  'sheet-footer': '.theme-sheet-footer',
  'tooltip-content': '.theme-tooltip-content',
  'tooltip-arrow': '.theme-tooltip-arrow',
  'hover-card-content': '.theme-hover-card-content',
  'confirm-dialog': '.theme-confirm-dialog',
  'confirm-title': '.theme-confirm-title',
  'confirm-description': '.theme-confirm-description',
  'confirm-button': '.theme-confirm-button',
  'confirm-cancel': '.theme-confirm-cancel',
  'confirm-secondary': '.theme-confirm-secondary',
  'sheet-top': '.theme-sheet-content[data-side="top"]',
  'sheet-bottom': '.theme-sheet-content[data-side="bottom"]',
  'sheet-left': '.theme-sheet-content[data-side="left"]',
  'sheet-right': '.theme-sheet-content[data-side="right"]',
  'permission-menu': '.theme-permission-menu',
  'permission-option': '.theme-permission-option',
  'model-menu': '.theme-model-menu',
  'selector-option-title': '.theme-selector-option-title',
  'selector-option-description': '.theme-selector-option-description',
  'market-card': '.theme-market-card',
  'market-card-header': '.theme-market-card-header',
  'market-card-content': '.theme-market-card-content',
  'market-card-footer': '.theme-market-card-footer',
  'market-card-title': '.theme-market-card-title',
  'market-card-description': '.theme-market-card-description',
  'shortcut-input': '.theme-shortcut-input',
  'shortcut-recording': '.theme-shortcut-recording',
  'send-shortcut-trigger': '.theme-send-shortcut-trigger',
  'send-shortcut-popup': '.theme-send-shortcut-popup',
  'send-shortcut-option': '.theme-send-shortcut-option',
  'auth-choice': '.theme-auth-choice',
  'code-header-button': '.theme-code-header-button',
  'code-hint': '.theme-code-hint',
  input: '.theme-input',
  textarea: '.theme-textarea',
  'input-embedded': '.theme-input-embedded',
  'action-compact': '.theme-action-compact',
  'action-icon-muted': '.theme-action-icon-muted',
  'action-inline-underlined': '.theme-action-inline-underlined',
  'control-inline-edit': '.theme-control-inline-edit',
  'control-small-text': '.theme-control-small-text',
  'control-muted': '.theme-control-muted',
  'action-inline-link': '.theme-action-inline-link',
  'action-faint': '.theme-action-faint',
  'action-muted': '.theme-action-muted',
  'action-row-large': '.theme-action-row-large',
  'control-compact-field': '.theme-control-compact-field',
  'action-row': '.theme-action-row',
  'action-muted-accent': '.theme-action-muted-accent',
  'action-compact-danger': '.theme-action-compact-danger',
  'action-inline-danger': '.theme-action-inline-danger',
  'action-overlay-compact': '.theme-action-overlay-compact',
  'action-small': '.theme-action-small',
  'control-transparent': '.theme-control-transparent',
  'control-card-surface': '.theme-control-card-surface',
  'action-icon-small-muted': '.theme-action-icon-small-muted',
  'action-window': '.theme-action-window',
  'local-compact-action': '.theme-local-compact-action',
  'page-code-block-button-1': '.theme-page-code-block-button-1',
  'page-lazy-chunk-error-boundary-button-1': '.theme-page-lazy-chunk-error-boundary-button-1',
  'page-login-button-button-1': '.theme-page-login-button-button-1',
  'page-login-button-button-2': '.theme-page-login-button-button-2',
  'page-markdown-content-button-1': '.theme-page-markdown-content-button-1',
  'page-settings-button-1': '.theme-page-settings-button-1',
  'page-settings-button-2': '.theme-page-settings-button-2',
  'page-settings-button-3': '.theme-page-settings-button-3',
  'page-settings-button-4': '.theme-page-settings-button-4',
  'page-settings-button-5': '.theme-page-settings-button-5',
  'page-settings-button-6': '.theme-page-settings-button-6',
  'page-settings-button-7': '.theme-page-settings-button-7',
  'page-settings-input-1': '.theme-page-settings-input-1',
  'page-settings-button-8': '.theme-page-settings-button-8',
  'page-settings-button-9': '.theme-page-settings-button-9',
  'page-settings-button-10': '.theme-page-settings-button-10',
  'page-settings-input-2': '.theme-page-settings-input-2',
  'page-settings-input-3': '.theme-page-settings-input-3',
  'page-settings-input-4': '.theme-page-settings-input-4',
  'page-settings-textarea-1': '.theme-page-settings-textarea-1',
  'page-settings-button-11': '.theme-page-settings-button-11',
  'page-sidebar-button-1': '.theme-page-sidebar-button-1',
  'page-sidebar-button-2': '.theme-page-sidebar-button-2',
  'page-agent-task-row-input-1': '.theme-page-agent-task-row-input-1',
  'page-expand-agent-tasks-row-button-1': '.theme-page-expand-agent-tasks-row-button-1',
  'page-my-agent-sidebar-tree-button-1': '.theme-page-my-agent-sidebar-tree-button-1',
  'page-workspace-tree-node-button-1': '.theme-page-workspace-tree-node-button-1',
  'page-workspace-tree-node-button-2': '.theme-page-workspace-tree-node-button-2',
  'page-artifact-preview-card-button-1': '.theme-page-artifact-preview-card-button-1',
  'page-file-directory-view-input-1': '.theme-page-file-directory-view-input-1',
  'page-document-renderer-button-1': '.theme-page-document-renderer-button-1',
  'page-mermaid-renderer-button-1': '.theme-page-mermaid-renderer-button-1',
  'page-model-renderer-button-1': '.theme-page-model-renderer-button-1',
  'page-coding-activity-view-badge-1': '.theme-page-coding-activity-view-badge-1',
  'page-coding-workspace-sidebar-button-1': '.theme-page-coding-workspace-sidebar-button-1',
  'page-coding-workspace-sidebar-button-2': '.theme-page-coding-workspace-sidebar-button-2',
  'page-coding-workspace-sidebar-button-3': '.theme-page-coding-workspace-sidebar-button-3',
  'page-active-expert-badge-button-1': '.theme-page-active-expert-badge-button-1',
  'page-ask-user-question-card-textarea-1': '.theme-page-ask-user-question-card-textarea-1',
  'page-cowork-prompt-input-button-1': '.theme-page-cowork-prompt-input-button-1',
  'page-create-project-dialog-input-1': '.theme-page-create-project-dialog-input-1',
  'page-embedding-settings-section-button-1': '.theme-page-embedding-settings-section-button-1',
  'page-image-preview-modal-button-1': '.theme-page-image-preview-modal-button-1',
  'page-session-expert-picker-popover-content-1':
    '.theme-page-session-expert-picker-popover-content-1',
  'page-tool-card-button-1': '.theme-page-tool-card-button-1',
  'page-preset-expert-list-card-1': '.theme-page-preset-expert-list-card-1',
  'page-preset-expert-list-button-1': '.theme-page-preset-expert-list-button-1',
  'page-feishu-instance-settings-button-1': '.theme-page-feishu-instance-settings-button-1',
  'page-common-button-1': '.theme-page-common-button-1',
  'page-marketplace-download-sidebar-badge-1': '.theme-page-marketplace-download-sidebar-badge-1',
  'page-runtime-install-card-card-1': '.theme-page-runtime-install-card-card-1',
  'page-runtime-install-card-card-footer-1': '.theme-page-runtime-install-card-card-footer-1',
  'page-marketplace-panel-select-trigger-1': '.theme-page-marketplace-panel-select-trigger-1',
  'page-models-panel-card-title-1': '.theme-page-models-panel-card-title-1',
  'page-model-launch-log-window-badge-1': '.theme-page-model-launch-log-window-badge-1',
  'page-model-launch-log-window-badge-2': '.theme-page-model-launch-log-window-badge-2',
  'page-model-launch-log-window-badge-3': '.theme-page-model-launch-log-window-badge-3',
  'page-model-launch-log-window-badge-4': '.theme-page-model-launch-log-window-badge-4',
  'page-active-mcp-badge-dropdown-menu-item-1': '.theme-page-active-mcp-badge-dropdown-menu-item-1',
  'page-mcp-manager-button-1': '.theme-page-mcp-manager-button-1',
  'page-mcp-manager-button-2': '.theme-page-mcp-manager-button-2',
  'page-mcp-manager-button-3': '.theme-page-mcp-manager-button-3',
  'page-mcp-manager-button-4': '.theme-page-mcp-manager-button-4',
  'page-mcp-manager-button-5': '.theme-page-mcp-manager-button-5',
  'page-quick-action-bar-button-1': '.theme-page-quick-action-bar-button-1',
  'page-run-session-modal-dialog-content-1': '.theme-page-run-session-modal-dialog-content-1',
  'page-task-list-card-1': '.theme-page-task-list-card-1',
  'page-task-template-gallery-card-1': '.theme-page-task-template-gallery-card-1',
  'page-task-template-gallery-card-2': '.theme-page-task-template-gallery-card-2',
  'page-pi-runtime-model-config-select-trigger-1':
    '.theme-page-pi-runtime-model-config-select-trigger-1',
  'page-pi-runtime-model-config-select-trigger-2':
    '.theme-page-pi-runtime-model-config-select-trigger-2',
  'page-active-skill-badge-button-1': '.theme-page-active-skill-badge-button-1',
  'page-installed-skill-grid-card-1': '.theme-page-installed-skill-grid-card-1',
  'page-installed-skill-grid-button-1': '.theme-page-installed-skill-grid-button-1',
  'page-marketplace-skill-grid-button-1': '.theme-page-marketplace-skill-grid-button-1',
  'page-skill-document-dialog-button-1': '.theme-page-skill-document-dialog-button-1',
  'page-skill-security-report-button-1': '.theme-page-skill-security-report-button-1',
  'page-skill-security-report-button-2': '.theme-page-skill-security-report-button-2',
  'page-skills-manager-button-1': '.theme-page-skills-manager-button-1',
  'page-skills-manager-input-1': '.theme-page-skills-manager-input-1',
  'page-skills-manager-button-2': '.theme-page-skills-manager-button-2',
  'page-skills-popover-popover-content-1': '.theme-page-skills-popover-popover-content-1',
  'page-skills-popover-button-1': '.theme-page-skills-popover-button-1',
  'page-todo-task-detail-input-1': '.theme-page-todo-task-detail-input-1',
  'page-todo-view-input-1': '.theme-page-todo-view-input-1',
  'page-app-update-badge-button-1': '.theme-page-app-update-badge-button-1',
  'page-window-title-bar-button-1': '.theme-page-window-title-bar-button-1',
  'page-confirmation-button-1': '.theme-page-confirmation-button-1',
  'page-tool-badge-1': '.theme-page-tool-badge-1',
  'page-sidebar-sheet-content-1': '.theme-page-sidebar-sheet-content-1',
  'page-model-selector-select-trigger-variant-1':
    '.theme-page-model-selector-select-trigger-variant-1',
  'page-settings-button-variant-1': '.theme-page-settings-button-variant-1',
  'page-settings-button-variant-2': '.theme-page-settings-button-variant-2',
  'page-settings-button-variant-3': '.theme-page-settings-button-variant-3',
  'page-settings-button-variant-4': '.theme-page-settings-button-variant-4',
  'page-settings-button-variant-5': '.theme-page-settings-button-variant-5',
  'page-settings-button-variant-6': '.theme-page-settings-button-variant-6',
  'page-settings-input-variant-1': '.theme-page-settings-input-variant-1',
  'page-settings-input-variant-2': '.theme-page-settings-input-variant-2',
  'page-settings-input-variant-3': '.theme-page-settings-input-variant-3',
  'page-settings-button-variant-7': '.theme-page-settings-button-variant-7',
  'page-settings-button-variant-8': '.theme-page-settings-button-variant-8',
  'page-settings-button-variant-9': '.theme-page-settings-button-variant-9',
  'page-agent-task-row-button-variant-1': '.theme-page-agent-task-row-button-variant-1',
  'page-agent-task-row-button-variant-2': '.theme-page-agent-task-row-button-variant-2',
  'page-agent-task-row-button-variant-3': '.theme-page-agent-task-row-button-variant-3',
  'page-agent-task-row-button-variant-4': '.theme-page-agent-task-row-button-variant-4',
  'page-workspace-tree-node-button-variant-1': '.theme-page-workspace-tree-node-button-variant-1',
  'page-workspace-tree-node-button-variant-2': '.theme-page-workspace-tree-node-button-variant-2',
  'page-artifact-badge-button-variant-1': '.theme-page-artifact-badge-button-variant-1',
  'page-artifact-badge-button-variant-2': '.theme-page-artifact-badge-button-variant-2',
  'page-artifact-badge-button-variant-3': '.theme-page-artifact-badge-button-variant-3',
  'page-artifact-panel-button-variant-1': '.theme-page-artifact-panel-button-variant-1',
  'page-artifact-panel-button-variant-2': '.theme-page-artifact-panel-button-variant-2',
  'page-artifact-panel-button-variant-3': '.theme-page-artifact-panel-button-variant-3',
  'page-artifact-panel-button-variant-4': '.theme-page-artifact-panel-button-variant-4',
  'page-artifact-panel-button-variant-5': '.theme-page-artifact-panel-button-variant-5',
  'page-document-renderer-button-variant-1': '.theme-page-document-renderer-button-variant-1',
  'page-document-renderer-button-variant-2': '.theme-page-document-renderer-button-variant-2',
  'page-document-renderer-button-variant-3': '.theme-page-document-renderer-button-variant-3',
  'page-text-renderer-button-variant-1': '.theme-page-text-renderer-button-variant-1',
  'page-text-renderer-button-variant-2': '.theme-page-text-renderer-button-variant-2',
  'page-text-renderer-button-variant-3': '.theme-page-text-renderer-button-variant-3',
  'page-chat-skill-shortcuts-button-variant-1': '.theme-page-chat-skill-shortcuts-button-variant-1',
  'page-chat-skill-shortcuts-button-variant-2': '.theme-page-chat-skill-shortcuts-button-variant-2',
  'page-chat-skill-shortcuts-button-variant-3': '.theme-page-chat-skill-shortcuts-button-variant-3',
  'page-coding-workspace-sidebar-button-variant-1':
    '.theme-page-coding-workspace-sidebar-button-variant-1',
  'page-coding-workspace-sidebar-button-variant-2':
    '.theme-page-coding-workspace-sidebar-button-variant-2',
  'page-coding-workspace-sidebar-button-variant-3':
    '.theme-page-coding-workspace-sidebar-button-variant-3',
  'page-coding-workspace-sidebar-button-variant-4':
    '.theme-page-coding-workspace-sidebar-button-variant-4',
  'page-coding-workspace-sidebar-button-variant-5':
    '.theme-page-coding-workspace-sidebar-button-variant-5',
  'page-coding-workspace-sidebar-button-variant-6':
    '.theme-page-coding-workspace-sidebar-button-variant-6',
  'page-coding-workspace-sidebar-button-variant-7':
    '.theme-page-coding-workspace-sidebar-button-variant-7',
  'page-cowork-question-wizard-button-variant-1':
    '.theme-page-cowork-question-wizard-button-variant-1',
  'page-cowork-session-detail-button-variant-1':
    '.theme-page-cowork-session-detail-button-variant-1',
  'page-cowork-session-detail-button-variant-2':
    '.theme-page-cowork-session-detail-button-variant-2',
  'page-cowork-session-detail-button-variant-3':
    '.theme-page-cowork-session-detail-button-variant-3',
  'page-cowork-session-detail-button-variant-4':
    '.theme-page-cowork-session-detail-button-variant-4',
  'page-cowork-session-detail-button-variant-5':
    '.theme-page-cowork-session-detail-button-variant-5',
  'page-cowork-session-detail-button-variant-6':
    '.theme-page-cowork-session-detail-button-variant-6',
  'page-cowork-session-detail-button-variant-7':
    '.theme-page-cowork-session-detail-button-variant-7',
  'page-cowork-session-detail-button-variant-8':
    '.theme-page-cowork-session-detail-button-variant-8',
  'page-copy-button-button-variant-1': '.theme-page-copy-button-button-variant-1',
  'page-copy-button-button-variant-2': '.theme-page-copy-button-button-variant-2',
  'page-copy-button-button-variant-3': '.theme-page-copy-button-button-variant-3',
  'page-copy-button-button-variant-4': '.theme-page-copy-button-button-variant-4',
  'page-imsettings-button-variant-1': '.theme-page-imsettings-button-variant-1',
  'page-imsettings-button-variant-2': '.theme-page-imsettings-button-variant-2',
  'page-imsettings-button-variant-3': '.theme-page-imsettings-button-variant-3',
  'page-imsettings-button-variant-4': '.theme-page-imsettings-button-variant-4',
  'page-imsettings-button-variant-5': '.theme-page-imsettings-button-variant-5',
  'page-imsettings-button-variant-6': '.theme-page-imsettings-button-variant-6',
  'page-imsettings-button-variant-7': '.theme-page-imsettings-button-variant-7',
  'page-imsettings-button-variant-8': '.theme-page-imsettings-button-variant-8',
  'page-imsettings-button-variant-9': '.theme-page-imsettings-button-variant-9',
  'page-imsettings-button-variant-10': '.theme-page-imsettings-button-variant-10',
  'page-imsettings-button-variant-11': '.theme-page-imsettings-button-variant-11',
  'page-imsettings-button-variant-12': '.theme-page-imsettings-button-variant-12',
  'page-imsettings-button-variant-13': '.theme-page-imsettings-button-variant-13',
  'page-imsettings-button-variant-14': '.theme-page-imsettings-button-variant-14',
  'page-imsettings-button-variant-15': '.theme-page-imsettings-button-variant-15',
  'page-imsettings-button-variant-16': '.theme-page-imsettings-button-variant-16',
  'page-imsettings-button-variant-17': '.theme-page-imsettings-button-variant-17',
  'page-imsettings-button-variant-18': '.theme-page-imsettings-button-variant-18',
  'page-imsettings-button-variant-19': '.theme-page-imsettings-button-variant-19',
  'page-imsettings-button-variant-20': '.theme-page-imsettings-button-variant-20',
  'page-imsettings-button-variant-21': '.theme-page-imsettings-button-variant-21',
  'page-imsettings-button-variant-22': '.theme-page-imsettings-button-variant-22',
  'page-imsettings-button-variant-23': '.theme-page-imsettings-button-variant-23',
  'page-imsettings-button-variant-24': '.theme-page-imsettings-button-variant-24',
  'page-imsettings-button-variant-25': '.theme-page-imsettings-button-variant-25',
  'page-imsettings-button-variant-26': '.theme-page-imsettings-button-variant-26',
  'page-imsettings-button-variant-27': '.theme-page-imsettings-button-variant-27',
  'page-imsettings-button-variant-28': '.theme-page-imsettings-button-variant-28',
  'page-imsettings-button-variant-29': '.theme-page-imsettings-button-variant-29',
  'page-imsettings-button-variant-30': '.theme-page-imsettings-button-variant-30',
  'page-imsettings-button-variant-31': '.theme-page-imsettings-button-variant-31',
  'page-imsettings-button-variant-32': '.theme-page-imsettings-button-variant-32',
  'page-imsettings-button-variant-33': '.theme-page-imsettings-button-variant-33',
  'page-imsettings-button-variant-34': '.theme-page-imsettings-button-variant-34',
  'page-imsettings-button-variant-35': '.theme-page-imsettings-button-variant-35',
  'page-imsettings-button-variant-36': '.theme-page-imsettings-button-variant-36',
  'page-local-inference-view-button-variant-1': '.theme-page-local-inference-view-button-variant-1',
  'page-models-panel-card-variant-1': '.theme-page-models-panel-card-variant-1',
  'page-models-panel-card-variant-2': '.theme-page-models-panel-card-variant-2',
  'page-models-panel-card-variant-3': '.theme-page-models-panel-card-variant-3',
  'page-models-panel-card-variant-4': '.theme-page-models-panel-card-variant-4',
  'page-prompt-panel-button-variant-1': '.theme-page-prompt-panel-button-variant-1',
  'page-prompt-panel-button-variant-2': '.theme-page-prompt-panel-button-variant-2',
  'page-prompt-panel-button-variant-3': '.theme-page-prompt-panel-button-variant-3',
  'page-date-input-button-variant-1': '.theme-page-date-input-button-variant-1',
  'page-date-input-button-variant-2': '.theme-page-date-input-button-variant-2',
  'page-date-input-button-variant-3': '.theme-page-date-input-button-variant-3',
  'page-date-input-button-variant-4': '.theme-page-date-input-button-variant-4',
  'page-date-input-button-variant-5': '.theme-page-date-input-button-variant-5',
  'page-date-input-button-variant-6': '.theme-page-date-input-button-variant-6',
  'page-date-input-button-variant-7': '.theme-page-date-input-button-variant-7',
  'page-date-input-button-variant-8': '.theme-page-date-input-button-variant-8',
  'page-date-input-button-variant-9': '.theme-page-date-input-button-variant-9',
  'page-date-input-button-variant-10': '.theme-page-date-input-button-variant-10',
  'page-date-input-button-variant-11': '.theme-page-date-input-button-variant-11',
  'page-task-list-card-title-variant-1': '.theme-page-task-list-card-title-variant-1',
  'page-task-list-card-title-variant-2': '.theme-page-task-list-card-title-variant-2',
  'page-provider-model-discovery-button-button-variant-1':
    '.theme-page-provider-model-discovery-button-button-variant-1',
  'page-provider-model-discovery-button-button-variant-2':
    '.theme-page-provider-model-discovery-button-button-variant-2',
  'page-marketplace-skill-grid-card-variant-1': '.theme-page-marketplace-skill-grid-card-variant-1',
  'page-marketplace-skill-grid-card-variant-2': '.theme-page-marketplace-skill-grid-card-variant-2',
  'page-skills-manager-button-variant-1': '.theme-page-skills-manager-button-variant-1',
  'page-skills-manager-button-variant-2': '.theme-page-skills-manager-button-variant-2',
  'page-attachments-button-variant-1': '.theme-page-attachments-button-variant-1',
  'page-attachments-button-variant-2': '.theme-page-attachments-button-variant-2',
  'page-attachments-button-variant-3': '.theme-page-attachments-button-variant-3',
  'page-attachments-button-variant-4': '.theme-page-attachments-button-variant-4',
  'page-attachments-button-variant-5': '.theme-page-attachments-button-variant-5',
  'page-attachments-button-variant-6': '.theme-page-attachments-button-variant-6',
  'page-attachments-button-variant-7': '.theme-page-attachments-button-variant-7',
  'page-chain-of-thought-badge-variant-1': '.theme-page-chain-of-thought-badge-variant-1',
  'page-code-block-select-trigger-variant-1': '.theme-page-code-block-select-trigger-variant-1',
  'page-conversation-button-variant-1': '.theme-page-conversation-button-variant-1',
  'page-conversation-button-variant-2': '.theme-page-conversation-button-variant-2',
  'page-prompt-input-select-trigger-variant-1': '.theme-page-prompt-input-select-trigger-variant-1',
  'page-prompt-input-select-trigger-variant-2': '.theme-page-prompt-input-select-trigger-variant-2',
  'page-queue-button-variant-1': '.theme-page-queue-button-variant-1',
  'page-queue-button-variant-2': '.theme-page-queue-button-variant-2',
  'page-suggestion-button-variant-1': '.theme-page-suggestion-button-variant-1',
  'page-terminal-button-variant-1': '.theme-page-terminal-button-variant-1',
  'page-terminal-button-variant-2': '.theme-page-terminal-button-variant-2',
  'page-command-dialog-content-variant-1': '.theme-page-command-dialog-content-variant-1',
  'page-sidebar-input-variant-1': '.theme-page-sidebar-input-variant-1',
  'part-coding-agent-manager-dialog-header-1': '.theme-part-coding-agent-manager-dialog-header-1',
  'part-coding-agent-manager-dialog-footer-1': '.theme-part-coding-agent-manager-dialog-footer-1',
  'part-session-expert-picker-command-1': '.theme-part-session-expert-picker-command-1',
  'part-expert-detail-dialog-dialog-header-1': '.theme-part-expert-detail-dialog-dialog-header-1',
  'part-expert-detail-dialog-dialog-title-1': '.theme-part-expert-detail-dialog-dialog-title-1',
  'part-expert-detail-dialog-dialog-footer-1': '.theme-part-expert-detail-dialog-dialog-footer-1',
  'part-model-context-settings-modal-input-group-input-1':
    '.theme-part-model-context-settings-modal-input-group-input-1',
  'part-model-context-settings-modal-input-group-text-1':
    '.theme-part-model-context-settings-modal-input-group-text-1',
  'part-marketplace-panel-input-group-input-1': '.theme-part-marketplace-panel-input-group-input-1',
  'part-marketplace-panel-select-value-1': '.theme-part-marketplace-panel-select-value-1',
  'part-run-session-modal-dialog-header-1': '.theme-part-run-session-modal-dialog-header-1',
  'part-run-session-modal-dialog-title-1': '.theme-part-run-session-modal-dialog-title-1',
  'part-skills-popover-command-1': '.theme-part-skills-popover-command-1',
  'expert-search-group': '.theme-part-session-expert-picker-command-1 [data-slot="input-group"]',
  'skill-search-group': '.theme-part-skills-popover-command-1 [data-slot="input-group"]',
  'piece-size-select-1': '.theme-piece-size-select-1',
  'piece-size-select-2': '.theme-piece-size-select-2',
  'piece-size-select-3': '.theme-piece-size-select-3',
  'piece-size-select-4': '.theme-piece-size-select-4',
  'piece-size-select-5': '.theme-piece-size-select-5',
  'piece-size-select-6': '.theme-piece-size-select-6',
  'piece-size-popover-1': '.theme-piece-size-popover-1',
  'piece-size-command-1': '.theme-piece-size-command-1',
  'piece-size-command-2': '.theme-piece-size-command-2',
  'piece-size-command-3': '.theme-piece-size-command-3',
  'piece-size-command-4': '.theme-piece-size-command-4',
  'piece-size-command-5': '.theme-piece-size-command-5',
  'piece-size-dropdown-menu-1': '.theme-piece-size-dropdown-menu-1',
  'piece-size-tooltip-1': '.theme-piece-size-tooltip-1',
  'piece-size-hover-card-1': '.theme-piece-size-hover-card-1',
  'command-list': '.theme-command-list',
  'menu-positioner': '.theme-menu-positioner',
  'editor-search-nav-icon': '.cm-editor.cm-editor .cm-search-nav-btn svg',
  'editor-search-close-icon': '.cm-editor.cm-editor .cm-search-close-btn svg',
  'fold-compact': '.theme-fold-compact',
  'fold-settings': '.theme-fold-settings',
  'fold-reasoning': '.theme-fold-reasoning',
  'message-body': '.theme-message-body',
  'queue-body': '.theme-queue-body',
  'queue-body-completed': '.theme-queue-body-completed',
  'reasoning-panel': '.theme-reasoning-panel',
  'reasoning-panel-indented': '.theme-reasoning-panel-indented',
  'reasoning-panel-open': '.theme-reasoning-panel[data-state="open"]',
  'reasoning-panel-closed': '.theme-reasoning-panel[data-state="closed"]',
  'input-submit': '.theme-input-submit',
  'control-content-height': '.theme-control-content-height',
  'composition-button-icon': '.theme-button svg:not([class*="size-"])',
  'composition-button-icon-xs':
    ':is(.theme-button-size-xs,.theme-button-size-icon-xs) svg:not([class*="size-"])',
  'composition-button-icon-sm': '.theme-button-size-sm svg:not([class*="size-"])',
  'composition-model-outline': '.theme-composition-model-outline',

  'control-sizing-1': '.theme-control-sizing-1',
  'control-sizing-2': '.theme-control-sizing-2',
  'control-sizing-3': '.theme-control-sizing-3',
  'control-sizing-4': '.theme-control-sizing-4',
  'control-sizing-5': '.theme-control-sizing-5',
  'control-sizing-6': '.theme-control-sizing-6',
  'control-sizing-7': '.theme-control-sizing-7',
  'control-sizing-8': '.theme-control-sizing-8',
  'control-sizing-9': '.theme-control-sizing-9',
  'control-sizing-10': '.theme-control-sizing-10',
  'control-sizing-11': '.theme-control-sizing-11',
  'control-sizing-12': '.theme-control-sizing-12',
  'control-sizing-13': '.theme-control-sizing-13',
  'control-sizing-14': '.theme-control-sizing-14',
  'control-sizing-15': '.theme-control-sizing-15',
  'control-sizing-16': '.theme-control-sizing-16',
  'control-sizing-17': '.theme-control-sizing-17',
  'control-sizing-18': '.theme-control-sizing-18',
  'control-sizing-19': '.theme-control-sizing-19',
  'control-sizing-20': '.theme-control-sizing-20',
  'control-sizing-21': '.theme-control-sizing-21',
  'control-sizing-22': '.theme-control-sizing-22',
  'control-sizing-23': '.theme-control-sizing-23',
  'control-sizing-24': '.theme-control-sizing-24',
  'control-sizing-25': '.theme-control-sizing-25',
  'control-sizing-26': '.theme-control-sizing-26',
  'control-sizing-27': '.theme-control-sizing-27',
  'control-sizing-28': '.theme-control-sizing-28',
  'control-sizing-29': '.theme-control-sizing-29',
  'control-sizing-30': '.theme-control-sizing-30',
  'control-sizing-31': '.theme-control-sizing-31',
  'control-sizing-32': '.theme-control-sizing-32',
  'editor-search-custom': '.cm-editor.cm-editor .cm-search-custom',
  'editor-search-input': '.cm-editor.cm-editor .cm-search-input',
  'editor-search-count': '.cm-editor.cm-editor .cm-search-count',
  'editor-search-count--none': '.cm-editor.cm-editor .cm-search-count--none',
  'editor-search-nav-btn': '.cm-editor.cm-editor .cm-search-nav-btn',
  'editor-search-sep': '.cm-editor.cm-editor .cm-search-sep',
  'editor-search-opt': '.cm-editor.cm-editor .cm-search-opt',
  'editor-search-opt-checkbox': '.cm-editor.cm-editor .cm-search-opt input[type="checkbox"]',
  'editor-search-close-btn': '.cm-editor.cm-editor .cm-search-close-btn',
  'surface-skill-token': '.theme-surface-skill-token',
  'surface-skill-icon': '.theme-surface-skill-icon',
  'surface-skill-fallback': '.theme-surface-skill-fallback',
  'surface-skill-remove': '.theme-surface-skill-remove',

  'surface-code-preview': '.theme-surface-code-preview',
  'surface-markdown-link': '.theme-surface-markdown-link',
  'surface-provider-row': '.theme-surface-provider-row',
  'surface-provider-selected': '.theme-surface-provider-selected',
  'surface-provider-idle': '.theme-surface-provider-idle',
  'surface-provider-link': '.theme-surface-provider-link',
  'surface-settings-row': '.theme-surface-settings-row',
  'surface-settings-link': '.theme-surface-settings-link',
  'surface-activity-row': '.theme-surface-activity-row',
  'surface-activity-expandable': '.theme-surface-activity-expandable',
  'surface-agent-row': '.theme-surface-agent-row',
  'surface-agent-selected': '.theme-surface-agent-selected',
  'surface-agent-idle': '.theme-surface-agent-idle',
  'surface-file-row': '.theme-surface-file-row',
  'surface-file-selected': '.theme-surface-file-selected',
  'surface-file-idle': '.theme-surface-file-idle',
  'surface-session-overlay': '.theme-surface-session-overlay',
  'surface-session-row': '.theme-surface-session-row',
  'surface-session-selected': '.theme-surface-session-selected',
  'surface-session-idle': '.theme-surface-session-idle',
  'surface-image-overlay': '.theme-surface-image-overlay',
  'surface-skill-editor': '.theme-surface-skill-editor',
  'surface-pending-row': '.theme-surface-pending-row',
  'surface-pending-selected': '.theme-surface-pending-selected',
  'surface-pending-failed': '.theme-surface-pending-failed',
  'surface-market-link': '.theme-surface-market-link',
  'surface-provider-dialog': '.theme-surface-provider-dialog',
  'surface-todo-row': '.theme-surface-todo-row',
  'surface-skill-placeholder': '.theme-surface-skill-editor:empty::before',
  'surface-pending-last': '.theme-surface-pending-row:last-child',
  'surface-agent-inactive':
    '[data-active-view]:not([data-active-view="cowork"]) .theme-surface-agent-selected',

  'native-slide': '.theme-native-slide',
  'native-slide-selected': '.theme-native-slide-selected',
  'native-slide-idle': '.theme-native-slide-idle',
  'native-activity-button': '.theme-native-activity-button',
  'native-workspace-action': '.theme-native-workspace-action',
  'native-field': '.theme-native-field',
  'native-question-field': '.theme-native-question-field',
  'native-rename-field': '.theme-native-rename-field',
  'native-audit-link': '.theme-native-audit-link',
  'native-audit-row': '.theme-native-audit-row',
  'native-sidebar-rail': '.theme-native-sidebar-rail',
  'native-sidebar-rail-line': '.theme-native-sidebar-rail::after',
  'native-sidebar-offcanvas': '[data-collapsible="offcanvas"] .theme-native-sidebar-rail',

  'legacy-modal-backdrop': '.modal-backdrop',
  'legacy-modal-content': '.modal-content',
  'legacy-permission-inline-surface': '.theme-permission-inline-surface',
  'settings-modal-frame': '.theme-settings-modal-frame',
  'settings-modal-shell': '.theme-settings-modal-shell',
  'local-context-modal': '.theme-local-context-modal',
  'local-capability-modal': '.theme-local-capability-modal',
  'skill-modal-backdrop': '.theme-skill-modal-backdrop',
  'skill-security-modal': '.theme-skill-security-modal',
  'skill-import-modal': '.theme-skill-import-modal',
  'composer-near': '.input-aura::before',
  'composer-far': '.input-aura::after',

  'control-tooltip-kbd': '.theme-tooltip-content [data-slot="kbd"]',
  'control-command-search-icon': '.theme-command-search-icon',
  'control-card-first-image': '.theme-card > img:first-child',
  'control-card-last-image': '.theme-card > img:last-child',
  'control-dialog-link': '.theme-dialog-description a',

  'joined-text': '[data-slot="button-group-text"]',
  'joined-control': '[data-slot="button-group"] > [data-slot]',
  'joined-horizontal-start':
    '[data-slot="button-group"]:not([data-orientation="vertical"]) > [data-slot]:has(~ [data-slot])',
  'joined-horizontal-end':
    '[data-slot="button-group"]:not([data-orientation="vertical"]) > [data-slot] ~ [data-slot]',
  'joined-vertical-start':
    '[data-slot="button-group"][data-orientation="vertical"] > [data-slot]:has(~ [data-slot])',
  'joined-vertical-end':
    '[data-slot="button-group"][data-orientation="vertical"] > [data-slot] ~ [data-slot]',
  'joined-separator': '[data-slot="button-group-separator"]',
  'input-group-button': '.theme-input-group-button',
  'input-group-button-xs': '.theme-input-group-button[data-size="xs"]',
  'input-group-button-icon-xs': '.theme-input-group-button[data-size="icon-xs"]',
  'input-group-button-icon-sm': '.theme-input-group-button[data-size="icon-sm"]',
  'input-group-addon-disabled':
    '[data-slot="input-group"][data-disabled="true"] [data-slot="input-group-addon"]',
  'input-group-addon-kbd': '[data-slot="input-group-addon"] > kbd',

  'workspace-row-button': '[data-slot="workspace-tree-row"] > [data-slot="button"]',
  'local-model-action': '[data-local-inference-model-action-button="true"]',
  'local-launch-status': '[data-local-inference-launch-status]',
  'local-launch-starting': '[data-local-inference-launch-status="starting"]',
  'local-launch-succeeded': '[data-local-inference-launch-status="succeeded"]',
  'local-launch-failed': '[data-local-inference-launch-status="failed"]',
  'local-launch-close': '[data-slot="button"][data-local-inference-launch-close-button="true"]',
  'local-launch-close-icon':
    '[data-local-inference-launch-close-button="true"]:hover:not(:disabled) svg',
  'local-secondary-action': '[data-local-inference-secondary-action-button="true"]',
  'local-secondary-icon': '[data-local-inference-secondary-action-button="true"] svg',
  'local-unload-action': '[data-slot="button"][data-local-inference-unload-button="true"]',
  'local-delete-confirm': '[data-slot="button"][data-local-inference-delete-confirm-button="true"]',
  'local-delete-action':
    '[data-slot="button"][data-local-inference-delete-confirm-action-button="true"]',
  'local-delete-cancel':
    '[data-slot="button"][data-local-inference-delete-confirm-action-button="true"]:not([data-local-inference-delete-confirm-button="true"])',
  'todo-queue-trigger': '[data-todo-queue-trigger="true"]',
  'composition-button-leading':
    ':is(.theme-button-size-default,.theme-button-size-lg):has([data-icon="inline-start"])',
  'composition-button-trailing':
    ':is(.theme-button-size-default,.theme-button-size-lg):has([data-icon="inline-end"])',
  'composition-button-small-leading':
    ':is(.theme-button-size-xs,.theme-button-size-sm):has([data-icon="inline-start"])',
  'composition-button-small-trailing':
    ':is(.theme-button-size-xs,.theme-button-size-sm):has([data-icon="inline-end"])',
  'composition-card-footer': '.theme-card:has([data-slot="card-footer"])',
  'composition-card-image': '.theme-card:has(>img:first-child)',
  'composition-card-header-border': '.theme-card-header.border-b',
  'composition-market-footer': '.theme-market-card:has([data-slot="card-footer"])',
  'group-spacing-addon': '.theme-input-group-addon',
  'group-spacing-inline-start': '.theme-input-group-addon[data-align="inline-start"]',
  'group-spacing-inline-end': '.theme-input-group-addon[data-align="inline-end"]',
  'group-spacing-block-start': '.theme-input-group-addon[data-align="block-start"]',
  'group-spacing-block-end': '.theme-input-group-addon[data-align="block-end"]',
  'group-spacing-start-border': '.theme-input-group-addon[data-align="block-start"].border-b',
  'group-spacing-end-border': '.theme-input-group-addon[data-align="block-end"].border-t',
  'group-spacing-input-top': '.theme-input-group:has(>[data-align="block-end"]) > input',
  'group-spacing-input-bottom': '.theme-input-group:has(>[data-align="block-start"]) > input',
  'group-spacing-input-right': '.theme-input-group:has(>[data-align="inline-end"]) > input',
  'group-spacing-input-left': '.theme-input-group:has(>[data-align="inline-start"]) > input',
  'control-standard-icon':
    ':is(.theme-select-trigger,.theme-select-item,.theme-select-scroll,.theme-menu-item,.theme-command-item,.theme-input-group-text,[data-slot="button-group-text"]) svg:not([class*="size-"])',
  'control-addon-icon': '.theme-input-group-addon > svg:not([class*="size-"])',
  'control-group-button-xs-icon':
    '.theme-input-group-button[data-size="xs"] > svg:not([class*="size-"])',
  'control-badge-leading': '.theme-badge:has([data-icon="inline-start"])',
  'control-badge-trailing': '.theme-badge:has([data-icon="inline-end"])',
  'control-tooltip-kbd-inset': '.theme-tooltip-content:has([data-slot="kbd"])',
  'control-command-addon-inset': '.theme-command-input-group > [data-slot="input-group-addon"]',
  'control-sheet-bottom-border': '.theme-sheet-content[data-side="bottom"]',
  'control-sheet-left-border': '.theme-sheet-content[data-side="left"]',
  'control-sheet-right-border': '.theme-sheet-content[data-side="right"]',
  'control-sheet-top-border': '.theme-sheet-content[data-side="top"]',
  'prompt-compact-action': '.theme-prompt-compact-action',
  'prompt-raised-action': '.theme-prompt-raised-action',
  'prompt-hover-action': '.theme-prompt-hover-action',
  'prompt-folder-action': '.theme-prompt-folder-action',
  'prompt-folder-warning': '.theme-prompt-folder-warning',
  'prompt-expert-chip': '.theme-prompt-expert-chip',
  'prompt-skills-action': '.theme-prompt-skills-action',
  'sidebar-common-surface': '.sidebar-interactive-surface',
  'sidebar-common-active': '.sidebar-interactive-surface-active',
  'sidebar-common-inactive':
    '[data-active-view]:not([data-active-view="cowork"]) .sidebar-session-row.sidebar-interactive-surface-active',
  'composer-surface': '.theme-composer-surface',
  'composer-drop-active': '.theme-composer-drop-active',
  'message-code-user': '.theme-message-code-user',
  'message-cowork-user': '.theme-message-cowork-user',
  'queue-question-content': '.theme-queue-question-content',
  'queue-acceptance-content': '.theme-queue-acceptance-content',
  'composer-input-surface': '.theme-composer-surface [data-slot="input-group"]',
  'message-role-user': '.group.is-user .theme-message-body',
  'message-role-assistant': '.group.is-assistant .theme-message-body',
  'tabs-list': '.theme-tabs-list',
  'tabs-list-horizontal': '[data-slot="tabs"][data-orientation="horizontal"] .theme-tabs-list',
  'tabs-list-default': '.theme-tabs-list-default',
  'tabs-list-line': '.theme-tabs-list-line',
  'tabs-trigger': '.theme-tabs-trigger',
  'tabs-default-trigger': '.theme-tabs-list-default .theme-tabs-trigger',
  'tabs-line-trigger': '.theme-tabs-list-line .theme-tabs-trigger',
  'tabs-trigger-leading': '.theme-tabs-trigger:has([data-icon="inline-start"])',
  'tabs-trigger-trailing': '.theme-tabs-trigger:has([data-icon="inline-end"])',
  'tabs-trigger-icon': '.theme-tabs-trigger svg:not([class*="size-"])',
  'tabs-trigger-indicator': '.theme-tabs-trigger::after',
  'tabs-line-indicator': '.theme-tabs-list-line .theme-tabs-trigger::after',
  'tabs-horizontal-indicator':
    '[data-slot="tabs"][data-orientation="horizontal"] .theme-tabs-trigger::after',
  'tabs-vertical-indicator':
    '[data-slot="tabs"][data-orientation="vertical"] .theme-tabs-trigger::after',
  'tabs-content': '.theme-tabs-content',
  'page-tabs-list': '.theme-page-tabs-list',
  'page-tabs-trigger': '.theme-page-tabs-trigger',
  'page-tabs-indicator': '.theme-page-tabs-indicator',
} as const;

const enabled =
  ':not(:disabled):not([aria-disabled="true"]):not([data-disabled=""]):not([data-disabled="true"])';
/** Ordered by precedence: invalid and disabled win over hover and focus. */
export const COMPONENT_STATES = {
  base: '',
  motionStart: '',
  motionEnd: '',
  wide: '',
  fileButton: '::file-selector-button',
  hover: `${enabled}:hover`,
  pressed: `${enabled}:active:not([aria-haspopup])`,
  selected:
    ':is([aria-selected="true"], [aria-pressed="true"], [data-selected=""], [data-selected="true"], [data-active="true"])',
  checked: ':is([aria-checked="true"], [data-checked])',
  expanded: ':is([aria-expanded="true"], [data-open], [data-popup-open], [data-state="open"])',
  focused: `${enabled}:focus`,
  focusHover: `${enabled}:focus:hover`,
  parentHover: ':is(.group:hover *)',
  parentFocus: ':is(.group:focus-within *)',
  focus: `${enabled}:focus-visible`,
  invalid: ':is([aria-invalid="true"], [data-invalid])',
  disabled: ':is(:disabled, [aria-disabled="true"], [data-disabled=""], [data-disabled="true"])',
  placeholder: '::placeholder',
  entering: '[data-starting-style]',
  exiting: '[data-ending-style]',
  empty: '[data-placeholder]',
  composerFocus: ':has(:is([data-slot="input-group-control"], [contenteditable]):focus-visible)',
  groupFocus: ':has([data-slot="input-group-control"]:focus-visible)',
  groupInvalid: ':has([data-slot][aria-invalid="true"])',
  groupDisabled: ':has([data-slot="input-group-control"]:disabled)',
  highlighted: `${enabled}:is([data-highlighted], [data-selected="true"])`,
} as const;

/** Only appearance properties; layout, hit testing and accessibility stay in components. */
export const APPEARANCE_PROPERTIES = [
  '--zy-control-icon-size',
  'color',
  'fill',
  'background-color',
  'border-color',
  'border-width',
  'border-style',
  'border-radius',
  'border-top-left-radius',
  'border-top-right-radius',
  'border-bottom-left-radius',
  'border-bottom-right-radius',
  'border-top-width',
  'border-left-width',
  'border-right-width',
  'border-bottom-width',
  'border-top-color',
  'box-shadow',
  'outline-color',
  'outline-width',
  'outline-style',
  'outline-offset',
  'opacity',
  'font-family',
  'font-variant-numeric',
  'accent-color',
  'font-size',
  'font-weight',
  'line-height',
  'text-decoration',
  'text-decoration-color',
  'backdrop-filter',
  'text-underline-offset',
  'animation-name',
  'animation-duration',
  'animation-delay',
  'animation-timing-function',
  'animation-iteration-count',
  'animation-direction',
  'animation-fill-mode',
  'transition-property',
  'transition-duration',
  'transition-timing-function',
  'height',
  'min-height',
  'width',
  'padding',
  'padding-left',
  'padding-right',
  'padding-top',
  'padding-bottom',
  'padding-inline',
  'padding-block',
  'padding-inline-start',
  'padding-inline-end',
  'gap',
  'translate',
  'scale',
] as const;
export type AppearanceStyle = Partial<Record<(typeof APPEARANCE_PROPERTIES)[number], string>>;
export type ComponentState = keyof typeof COMPONENT_STATES;
/** Empty states explicitly inherit the base appearance (e.g. pressed text fields). */
export type ComponentAppearance = Record<ComponentState, AppearanceStyle>;
export type ComponentAppearances = Record<keyof typeof COMPONENT_SELECTORS, ComponentAppearance>;

export function validateComponentAppearances(components: ComponentAppearances): void {
  if (!components || typeof components !== 'object')
    throw new Error('Missing component appearances');
  for (const name of Object.keys(components)) {
    if (!Object.hasOwn(COMPONENT_SELECTORS, name))
      throw new Error(`Unknown component appearance: ${name}`);
  }
  for (const name of Object.keys(COMPONENT_SELECTORS) as (keyof ComponentAppearances)[]) {
    const recipe = components[name];
    if (!recipe || typeof recipe !== 'object')
      throw new Error(`Missing component appearance: ${name}`);
    for (const state of Object.keys(recipe)) {
      if (!Object.hasOwn(COMPONENT_STATES, state))
        throw new Error(`Unknown component state: ${state}`);
    }
    for (const state of Object.keys(COMPONENT_STATES) as ComponentState[]) {
      const declarations = recipe[state];
      if (!declarations || typeof declarations !== 'object' || Array.isArray(declarations)) {
        throw new Error(`Missing component state: ${name}.${state}`);
      }
      for (const [property, value] of Object.entries(declarations)) {
        if (
          (state === 'motionStart' || state === 'motionEnd') &&
          !['opacity', 'scale', 'translate'].includes(property)
        ) {
          throw new Error(`Invalid component motion property: ${property}`);
        }
        if (!APPEARANCE_PROPERTIES.includes(property as never))
          throw new Error(`Invalid appearance property: ${property}`);
        if (
          typeof value !== 'string' ||
          !value.trim() ||
          /[;{}<>\\]|url\s*\(|@|!important|expression\s*\(/i.test(value)
        ) {
          throw new Error(`Invalid appearance value: ${name}.${state}.${property}`);
        }
        if (property === 'animation-name' && value !== 'none' && value !== 'component-motion') {
          throw new Error(`Unknown component animation: ${value}`);
        }
        if (
          property === 'animation-name' &&
          value === 'component-motion' &&
          (!recipe.motionStart ||
            !Object.keys(recipe.motionStart).length ||
            !recipe.motionEnd ||
            !Object.keys(recipe.motionEnd).length)
        ) {
          throw new Error(`Missing component motion frames: ${name}`);
        }
        for (const match of value.matchAll(/var\(\s*(--[a-zA-Z0-9-]+)/g)) {
          if (!appearanceVariables.has(match[1]))
            throw new Error(`Unknown appearance variable: ${match[1]}`);
        }
      }
    }
  }
}

/** Fixed integration hooks whose vendor defaults are emitted outside cascade layers. */
export const EXTERNAL_COMPONENTS = new Set<string>([
  'editor-search-nav-icon',
  'editor-search-close-icon',
  'editor-search-custom',
  'editor-search-input',
  'editor-search-count',
  'editor-search-count--none',
  'editor-search-nav-btn',
  'editor-search-sep',
  'editor-search-opt',
  'editor-search-opt-checkbox',
  'editor-search-close-btn',
]);
